### ISSUE TITLE
Latest parsers aren't available

### ISSUE THREAD

**Issue by khallmark** [Davnit/ESMapV2#13]
Hello @Davnit! I really love ESMap. I was trying to setup my own instance so I could make some improvements for mobile + containerize it. 

Can you make sure the source is up to date so I can open pull requests?

**Comment by Davnit** [comment]
Hey thanks for your interest. I kind of just published this once it was "done and stable" and I'm pretty terrible at keeping up with version control so I've just been doing all the hot patching directly on the server.

I really don't like PHP and Google Maps is costing me 4 figures annually so I'm currently in the midst of a major rewrite that'll put the whole server into a Python/Flask app using OpenStreetMap & Leaflet.js and then the client component will be mostly the same as it is now. That being said I wouldn't waste any time on the current code since I wrote it all so long ago I don't even remember how most of it works and have no intent to ever touch it again aside from quick fixes.

I will see about updating the parsers.

**Comment by khallmark** [comment]
Thanks! I mainly want to use the parsers locally to capture the data into a db locally. I'm really interested in doing some analysis on the dataset. Anything you can push up would be awesome.

**Comment by Davnit** [comment]
Here you go 384fc24, f925ce7
